### ISSUE TITLE
Making vizarr authentication errors more explicit

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-vizarr-viewer#30]
We now often see the following error:
```
Error: server replied with "Node not found: v3 array or group" when loading the resource
```

There can be various reasons for it and I keep getting questions on it from users, so it is something we should improve on after all.

This can occur because:
- A user doesn't have access to any vizarr data (in the current scheme: User isn't in the allowed users list)
- A user doesn't have access to that specific data
- The user isn't logged in to Fractal anymore (which isn't very obvious)

And probably many more scenarios :)

We should at least catch those first 3 and display relevant errors. If that means we'll need to make upstream contributions to be able to catch such errors at all, let's try that again. I'll go lobby for them if they get stuck again ;)

**Comment by tcompa** [comment]
Ref:
* https://github.com/fractal-analytics-platform/fractal-vizarr-viewer/issues/5#issuecomment-2242629699

**Comment by zonia3000** [comment]
See https://github.com/hms-dbmi/vizarr/pull/214
