### ISSUE TITLE
Introduce `AUTHORIZATION_SCHEME="fractal-server-viewer-paths"`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-vizarr-viewer#31]
Requires:
* https://github.com/fractal-analytics-platform/fractal-server/issues/1809

In a future fractal-server version, a standard user will have the possibility to make an API call and get back a list of some base paths (typically one or a handful of them) that they can access via fractal-vizarr-viewer. This should then be used by fractal-vizarr-viewer authorization component to verify if the requested path belongs to one of those base paths - and raise an error if it does not.

The endpoint to be called is `GET /auth/current-user/viewer-paths/`, which will return a list of absolute paths where the current-user is authorized to view files/zarrs.

**Comment by tcompa** [comment]
Available as of fractal-server 2.6.3.

**Comment by zonia3000** [comment]
Using this scheme is the `ZARR_DATA_BASE_PATH` still required?

**Comment by tcompa** [comment]
> Using this scheme is the ZARR_DATA_BASE_PATH still required?

No.
Within this scheme, the paths coming from fractal-server are considered as trustworthy.
