### ISSUE TITLE
Include `user_settings.project_dir` in list of allowed paths, on top of `usergroup.viewer_paths`

### ISSUE THREAD

**Issue by ychiucco** [fractal-analytics-platform/fractal-vizarr-viewer#44]
ref https://github.com/fractal-analytics-platform/fractal-server/issues/1934
ref https://github.com/fractal-analytics-platform/fractal-server/issues/1986

from https://github.com/fractal-analytics-platform/fractal-server/issues/1934#issuecomment-2446689635
```
How does it match with the `user_group.viewer_paths`?
These are per user group. Do we add the `user.project_dir` to the things a user has access to?
Some potential complexities in whether users would have access to all their `zarr_dir`s
```

**Comment by jluethi** [comment]
Let's be careful here that we add the admin-set `user.project_dir`, not all `dataset.zarr_dir`. Because a user could set those to anything and thus gain access to data they shouldn't if we use them in access management
