### ISSUE TITLE
Should `project_dir` also affect the `users-folder` authorizer?

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-vizarr-viewer#48]

**Comment by zonia3000** [comment]
So, I'm going to apply the following logic: allow the access if the requested path is inside `project_dir` or inside `ZARR_DATA_BASE_PATH/slurm_user`. This means that `project_dir` can be defined outside `ZARR_DATA_BASE_PATH`.
Is that correct?
