### ISSUE TITLE
Review how vizarr works as of recent switch from zarr.js to zarrita.js

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-vizarr-viewer#5]
The obvious question is whether a patch similar to https://github.com/gzuidhof/zarr.js/pull/151 would be needed for zarrita.js as well.

**Comment by zonia3000** [comment]
In #15 I've added the changes for using the newer vizarr version, that also switched from `npm` to `pnpm`. It looks that it is mandatory to use `pnpm` to build the package. I suggest to install it using `npm install -g pnpm`.

Moreover the vizarr output folder is now called `dist` and not `out`. I've updated the information on the README.

**Comment by tcompa** [comment]
No further activity needed on this one, for the moment. We are aware that the error message may be suboptimal - as described above.
